# !!! this should also update the milestones

name: update materials

on: workflow_dispatch

jobs:
  update-materials:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: npm install

      - run:
          'npm run sac:update-materials -- repo=${{ github.event.repository.name
          }} user=${{ github.repository_owner }}'

      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.7.2
        with:
          commit_message: update materials
          branch: ${{ github.head_ref }}
